// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// IMPORTANT: Use your Supabase project's URL + anon (public) key here.
// This avoids any mismatch between local .env and Vercel env and guarantees
// every request includes a valid `apikey` header.
const SUPABASE_URL = "https://rrxsevbgtprbtfakidqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_e5udXFWl7w_gMFH_ezq-pg_Fx8KvzWd";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});